### ISSUE TITLE
add_repository doesn't manage https source urls

### ISSUE THREAD

**Issue by sgaravat** [cvmfs-contrib/cvmfs-manage-replicas#9]
add_repository doesn't manage https source URL (this can be needed e.g. for a S3 backend)

This piece of code:

```
case "$2" in
    http://*) REPOURL="$2/cvmfs/$REPONAME";;
    continue) CREATEREPO=false;;
    *)  usage ;;
esac

```

should be replaced with something like (I am not able to find the right glob expression):

```
case "$2" in
    http://*) REPOURL="$2/cvmfs/$REPONAME";;
    https://*) REPOURL="$2/cvmfs/$REPONAME";;
    continue) CREATEREPO=false;;
    *)  usage ;;
esac



```

**Comment by DrDaveD** [comment]
How about just changing `http://*` to `http*://*`.  Does that work for you?

**Comment by sgaravat** [comment]
Yes: http*://* works as well
Thanks, Massimo

**Comment by DrDaveD** [comment]
So it will be in the next release.  Do you need me to make a new release or is it good enough for you to work with a hacked copy until then?

**Comment by sgaravat** [comment]
Thank you !
Yes: I can live with the hacked copy waiting for the new release
